language: php

php:
    - 5.6
    - 7

cache:
    directories:
        - $HOME/.composer/cache

install:
    - composer install

script:
    - vendor/bin/php-cs-fixer fix --dry-run --diff
    - phpunit

sudo: false